#Global parameters module

N = 1024
K = 16
Q = 12289
POLY_BYTES = 1792
NEWHOPE_SEEDBYTES = 32
NEWHOPE_RECBYTES = 256
NEWHOPE_SENDABYTES = POLY_BYTES + NEWHOPE_SEEDBYTES
NEWHOPE_SENDBBYTES = POLY_BYTES + NEWHOPE_RECBYTES
